#include "ui.h"
#include "pixel_font.h"
#include "icons.h"
#include "calc.h"
#include "localization.h"
#include "milestones.h"
#include <string.h>

typedef enum {VIEW_HOME,VIEW_CONFIRM,VIEW_ACH,VIEW_STATS,VIEW_SETTINGS,VIEW_ONBOARD,VIEW_PICKER,VIEW_NUMBER,VIEW_CURRENCY,VIEW_RESET,VIEW_HISTORY,VIEW_FLASH} View;
typedef enum {OB_LAST,OB_CIGS,OB_COST,OB_CUR,OB_DONE} OnboardStep;

static Window*s_window;static Layer*s_layer;static AppState*s;static AppLang lang;static View view;static OnboardStep ob;
static int row=0,anim=0,ach_index=-1,picker_field=0,num_value=20,intro_phase=0;static bool number_is_cost=false;static Currency cur_pick=CUR_USD;
static AppTimer*timer;static struct tm picker_tm;

static GColor fg(void){return GColorWhite;}static GColor bg(void){return GColorBlack;}static GColor dim(void){return PBL_IF_COLOR_ELSE(GColorDarkGray,GColorWhite);}static GColor accent(void){return PBL_IF_COLOR_ELSE(GColorMintGreen,GColorWhite);}
static void fill(GContext*c,GRect r,GColor col){graphics_context_set_fill_color(c,col);graphics_fill_rect(c,r,0,GCornerNone);}static void box(GContext*c,GRect r,GColor col){graphics_context_set_stroke_color(c,col);graphics_draw_rect(c,r);}
static void txt(GContext*c,const char*t,GRect r,int sc,GColor col,PixelAlign a){pixel_font_draw(c,t,r,pixel_font_fit_scale(t,r.size.w,sc,1),col,a);}
static void money(char*b,size_t n,int cents){const char*sym=s->currency==CUR_USD?"$":s->currency==CUR_EUR?"€":s->currency==CUR_PLN?"zł":"₽";snprintf(b,n,"%s%d.%02d",sym,cents/100,cents%100);}
static void header(GContext*c,GRect b){txt(c,"NOSMOKEBLLE",GRect(8,5,b.size.w-16,9),1,fg(),PF_ALIGN_LEFT);fill(c,GRect(b.size.w-12,7,3,3),accent());graphics_context_set_stroke_color(c,dim());graphics_draw_line(c,GPoint(8,16),GPoint(b.size.w-9,16));}
static void progress(GContext*c,GRect r,time_t e){int ni=milestone_next(e);if(ni<0){fill(c,r,accent());return;}int pi=milestone_prev(e);int32_t a=pi<0?0:MILESTONES[pi].seconds,b=MILESTONES[ni].seconds;int w=(int)(((int64_t)(e-a)*r.size.w)/(b-a));if(w<1)w=1;if(w>r.size.w)w=r.size.w;box(c,r,fg());if(w>2)fill(c,GRect(r.origin.x+1,r.origin.y+1,w-2,r.size.h-2),accent());}

static void draw_home(GContext*c,GRect b){
  header(c,b);if(intro_phase==0)return;Stats st=calc_stats(s,time(NULL));int d,h,m,se;calc_split_elapsed(st.elapsed,&d,&h,&m,&se);char a[24],bb[24],cv[24],mv[24],left[32];
  txt(c,loc(lang,"smoke_free"),GRect(8,20,b.size.w-16,12),1,accent(),PF_ALIGN_CENTER);if(intro_phase==1)return;snprintf(a,sizeof(a),"%02dD",d);txt(c,a,GRect(8,31,b.size.w-16,b.size.h>190?36:28),b.size.h>190?4:3,fg(),PF_ALIGN_CENTER);
  if(d>0)snprintf(bb,sizeof(bb),"%02d:%02d",h,m);else snprintf(bb,sizeof(bb),"%02d:%02d:%02d",h,m,se);txt(c,bb,GRect(8,b.size.h>190?68:59,b.size.w-16,24),2,fg(),PF_ALIGN_CENTER);if(intro_phase==2)return;
  int cy=b.size.h>190?94:84,cardw=(b.size.w-21)/2;box(c,GRect(7,cy,cardw,34),dim());icon_draw(c,ICON_CIG,GPoint(12,cy+5),1,accent());snprintf(cv,sizeof(cv),"%d",st.cigarettes_avoided);txt(c,cv,GRect(22,cy+3,cardw-18,14),2,fg(),PF_ALIGN_RIGHT);txt(c,loc(lang,"avoided"),GRect(11,cy+20,cardw-8,9),1,dim(),PF_ALIGN_LEFT);
  box(c,GRect(14+cardw,cy,cardw,34),dim());icon_draw(c,ICON_MONEY,GPoint(19+cardw,cy+5),1,accent());money(mv,sizeof(mv),st.saved_cents);txt(c,mv,GRect(29+cardw,cy+3,cardw-18,14),1,fg(),PF_ALIGN_RIGHT);txt(c,loc(lang,"saved"),GRect(18+cardw,cy+20,cardw-8,9),1,dim(),PF_ALIGN_LEFT);
  if(intro_phase==3)return;int gy=cy+40;txt(c,loc(lang,"goal"),GRect(8,gy,b.size.w-16,9),1,dim(),PF_ALIGN_LEFT);progress(c,GRect(8,gy+11,b.size.w-16,8),st.elapsed);int ni=milestone_next(st.elapsed);if(ni>=0){txt(c,milestone_title(ni,lang),GRect(8,gy+21,b.size.w/2-10,9),1,fg(),PF_ALIGN_LEFT);calc_format_compact(MILESTONES[ni].seconds-st.elapsed,left,sizeof(left));txt(c,left,GRect(b.size.w/2,gy+21,b.size.w/2-8,9),1,dim(),PF_ALIGN_RIGHT);}
  int hy=b.size.h-18;icon_draw(c,ICON_UP,GPoint(8,hy),1,dim());txt(c,loc(lang,"ach_short"),GRect(18,hy-1,54,9),1,dim(),PF_ALIGN_LEFT);icon_draw(c,ICON_DOWN,GPoint(b.size.w-74,hy),1,dim());txt(c,loc(lang,"stats"),GRect(b.size.w-62,hy-1,54,9),1,dim(),PF_ALIGN_RIGHT);icon_draw(c,ICON_SELECT,GPoint(b.size.w-8,cy+7),1,accent());
}
static void draw_confirm(GContext*c,GRect b){header(c,b);icon_draw(c,ICON_CIG,GPoint((b.size.w-15)/2,35),3,accent());txt(c,loc(lang,"confirm"),GRect(8,62,b.size.w-16,24),2,fg(),PF_ALIGN_CENTER);box(c,GRect(16,98,b.size.w-32,24),accent());txt(c,"SELECT",GRect(22,102,55,14),1,dim(),PF_ALIGN_LEFT);txt(c,loc(lang,"yes"),GRect(82,102,b.size.w-104,14),1,fg(),PF_ALIGN_RIGHT);box(c,GRect(16,128,b.size.w-32,24),dim());txt(c,"BACK",GRect(22,132,55,14),1,dim(),PF_ALIGN_LEFT);txt(c,loc(lang,"no"),GRect(82,132,b.size.w-104,14),1,fg(),PF_ALIGN_RIGHT);}
static void draw_achievements(GContext*c,GRect b){
  header(c,b);
  if(ach_index>=0){icon_draw(c,ICON_BURST,GPoint((b.size.w-15)/2,30),3,accent());txt(c,loc(lang,"achievement"),GRect(8,58,b.size.w-16,12),1,dim(),PF_ALIGN_CENTER);txt(c,milestone_title(ach_index,lang),GRect(8,76,b.size.w-16,22),2,fg(),PF_ALIGN_CENTER);pixel_font_draw_wrapped(c,milestone_desc(ach_index,lang),GRect(12,103,b.size.w-24,42),1,dim(),PF_ALIGN_CENTER,2);txt(c,"SELECT",GRect(8,b.size.h-15,b.size.w-16,9),1,accent(),PF_ALIGN_CENTER);return;}
  txt(c,loc(lang,"achievements"),GRect(8,20,b.size.w-16,14),1,accent(),PF_ALIGN_LEFT);time_t e=time(NULL)-s->last_smoked;int visible=(b.size.h-40)/22;if(row>MILESTONE_COUNT-visible)row=MILESTONE_COUNT-visible;if(row<0)row=0;
  for(int j=0;j<visible;j++){int i=row+j,y=38+j*22;bool ok=e>=MILESTONES[i].seconds;box(c,GRect(8,y,b.size.w-16,18),ok?fg():dim());icon_draw(c,ok?ICON_CHECK:ICON_LOCK,GPoint(12,y+5),1,ok?accent():dim());txt(c,milestone_title(i,lang),GRect(24,y+4,b.size.w-70,9),1,ok?fg():dim(),PF_ALIGN_LEFT);if(ok)txt(c,loc(lang,"completed"),GRect(b.size.w-62,y+4,52,9),1,dim(),PF_ALIGN_RIGHT);}
}
static void draw_stats(GContext*c,GRect b){header(c,b);txt(c,loc(lang,"stats"),GRect(8,20,b.size.w-16,12),1,accent(),PF_ALIGN_LEFT);Stats st=calc_stats(s,time(NULL));char v[32];const char*labs[5]={loc(lang,"current"),loc(lang,"best"),loc(lang,"attempts"),loc(lang,"total_cigs"),loc(lang,"total_saved")};int y=38;for(int i=0;i<5;i++){box(c,GRect(8,y,b.size.w-16,22),i==row?accent():dim());txt(c,labs[i],GRect(13,y+2,b.size.w-26,9),1,i==row?fg():dim(),PF_ALIGN_LEFT);if(i==0)calc_format_compact(st.elapsed,v,sizeof(v));else if(i==1)calc_format_compact(s->best_streak,v,sizeof(v));else if(i==2)snprintf(v,sizeof(v),"%d",s->attempts);else if(i==3)snprintf(v,sizeof(v),"%ld",(long)(s->lifetime_avoided_milli/1000)+st.cigarettes_avoided);else money(v,sizeof(v),(s->lifetime_saved_cents_milli/1000)+st.saved_cents);txt(c,v,GRect(13,y+11,b.size.w-26,9),1,fg(),PF_ALIGN_RIGHT);y+=24;}box(c,GRect(8,y,b.size.w-16,20),row==5?accent():dim());txt(c,loc(lang,"history"),GRect(13,y+6,b.size.w-26,9),1,row==5?fg():dim(),PF_ALIGN_LEFT);}
static void draw_history(GContext*c,GRect b){header(c,b);txt(c,loc(lang,"history"),GRect(8,20,b.size.w-16,12),1,accent(),PF_ALIGN_LEFT);if(!s->history_count){txt(c,loc(lang,"empty_history"),GRect(10,70,b.size.w-20,14),1,dim(),PF_ALIGN_CENTER);return;}int visible=(b.size.h-42)/28;if(row>(int)s->history_count-visible)row=s->history_count-visible;if(row<0)row=0;for(int j=0;j<visible&&j+row<s->history_count;j++){int logical=row+j;int idx=(s->history_head+HISTORY_MAX-1-logical)%HISTORY_MAX;AttemptRecord*r=&s->history[idx];char dur[28],saved[24],line[48];calc_format_compact(r->duration,dur,sizeof(dur));money(saved,sizeof(saved),r->saved_cents);snprintf(line,sizeof(line),"%s  %d  %s",dur,(int)r->avoided,saved);int y=38+j*28;box(c,GRect(8,y,b.size.w-16,23),logical==row?accent():dim());txt(c,line,GRect(13,y+7,b.size.w-26,9),1,fg(),PF_ALIGN_LEFT);}}
static const char*setting_name(int i){const char*k[]={"cigs_day","cost_day","currency","last_cig","reset"};return loc(lang,k[i]);}
static void draw_settings(GContext*c,GRect b){header(c,b);txt(c,loc(lang,"settings"),GRect(8,20,b.size.w-16,12),1,accent(),PF_ALIGN_LEFT);for(int i=0;i<5;i++){int y=40+i*26;box(c,GRect(8,y,b.size.w-16,21),i==row?accent():dim());txt(c,setting_name(i),GRect(13,y+6,b.size.w-26,9),1,i==row?fg():dim(),PF_ALIGN_LEFT);}}
static void draw_onboard(GContext*c,GRect b){header(c,b);if(ob==OB_LAST){txt(c,loc(lang,"when"),GRect(12,34,b.size.w-24,38),2,fg(),PF_ALIGN_CENTER);const char*opts[3]={loc(lang,"now"),loc(lang,"today"),loc(lang,"yesterday")};for(int i=0;i<3;i++){int y=84+i*28;box(c,GRect(24,y,b.size.w-48,22),i==row?accent():dim());txt(c,opts[i],GRect(28,y+6,b.size.w-56,9),1,fg(),PF_ALIGN_CENTER);}}else{txt(c,loc(lang,"ready"),GRect(8,55,b.size.w-16,25),3,accent(),PF_ALIGN_CENTER);txt(c,loc(lang,"start"),GRect(8,94,b.size.w-16,18),2,fg(),PF_ALIGN_CENTER);}}
static void draw_picker(GContext*c,GRect b){header(c,b);txt(c,loc(lang,"last_cig"),GRect(8,22,b.size.w-16,12),1,accent(),PF_ALIGN_CENTER);char d[20],t[12];static const char*mon[]={"JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"};snprintf(d,sizeof(d),"%02d %s %04d",picker_tm.tm_mday,mon[picker_tm.tm_mon],picker_tm.tm_year+1900);snprintf(t,sizeof(t),"%02d:%02d",picker_tm.tm_hour,picker_tm.tm_min);box(c,GRect(13,51,b.size.w-26,32),picker_field<3?accent():dim());txt(c,d,GRect(18,58,b.size.w-36,16),2,fg(),PF_ALIGN_CENTER);box(c,GRect(34,96,b.size.w-68,32),picker_field>=3?accent():dim());txt(c,t,GRect(39,103,b.size.w-78,16),2,fg(),PF_ALIGN_CENTER);icon_draw(c,ICON_UP,GPoint((b.size.w-5)/2,37),1,dim());icon_draw(c,ICON_DOWN,GPoint((b.size.w-5)/2,133),1,dim());txt(c,"SELECT >",GRect(8,b.size.h-15,b.size.w-16,9),1,dim(),PF_ALIGN_RIGHT);}
static void draw_number(GContext*c,GRect b){header(c,b);txt(c,loc(lang,number_is_cost?"cost_day":"cigs_day"),GRect(8,30,b.size.w-16,14),1,accent(),PF_ALIGN_CENTER);char v[24];if(number_is_cost)snprintf(v,sizeof(v),"$%d.%02d",num_value/100,num_value%100);else snprintf(v,sizeof(v),"%d",num_value);txt(c,v,GRect(8,63,b.size.w-16,38),4,fg(),PF_ALIGN_CENTER);icon_draw(c,ICON_UP,GPoint((b.size.w-5)/2,50),1,dim());icon_draw(c,ICON_DOWN,GPoint((b.size.w-5)/2,112),1,dim());txt(c,"SELECT",GRect(8,b.size.h-15,b.size.w-16,9),1,dim(),PF_ALIGN_CENTER);}
static const char*cur_name(Currency q){return q==CUR_USD?"USD $":q==CUR_EUR?"EUR €":q==CUR_PLN?"PLN zł":"RUB ₽";}
static void draw_currency(GContext*c,GRect b){header(c,b);txt(c,loc(lang,"currency"),GRect(8,24,b.size.w-16,12),1,accent(),PF_ALIGN_CENTER);for(int i=0;i<4;i++){int y=48+i*26;box(c,GRect(26,y,b.size.w-52,21),i==cur_pick?accent():dim());txt(c,cur_name((Currency)i),GRect(31,y+6,b.size.w-62,9),1,fg(),PF_ALIGN_CENTER);}}
static void draw_reset(GContext*c,GRect b){header(c,b);txt(c,loc(lang,"reset_q"),GRect(12,52,b.size.w-24,32),2,fg(),PF_ALIGN_CENTER);txt(c,"SELECT = YES",GRect(12,105,b.size.w-24,9),1,accent(),PF_ALIGN_CENTER);txt(c,"BACK = NO",GRect(12,124,b.size.w-24,9),1,dim(),PF_ALIGN_CENTER);}
static void draw_flash(GContext*c,GRect b){header(c,b);fill(c,GRect(10,35,b.size.w-20,b.size.h-70),anim%2?fg():accent());txt(c,loc(lang,"new_run"),GRect(14,70,b.size.w-28,24),2,bg(),PF_ALIGN_CENTER);}
static void update(Layer*l,GContext*c){GRect b=layer_get_bounds(l);fill(c,b,bg());switch(view){case VIEW_HOME:draw_home(c,b);break;case VIEW_CONFIRM:draw_confirm(c,b);break;case VIEW_ACH:draw_achievements(c,b);break;case VIEW_STATS:draw_stats(c,b);break;case VIEW_SETTINGS:draw_settings(c,b);break;case VIEW_ONBOARD:draw_onboard(c,b);break;case VIEW_PICKER:draw_picker(c,b);break;case VIEW_NUMBER:draw_number(c,b);break;case VIEW_CURRENCY:draw_currency(c,b);break;case VIEW_RESET:draw_reset(c,b);break;case VIEW_HISTORY:draw_history(c,b);break;default:draw_flash(c,b);}}
static void redraw(void){layer_mark_dirty(s_layer);}static void intro_tick(void*ctx){if(intro_phase<4){intro_phase++;redraw();app_timer_register(110,intro_tick,NULL);}}static void schedule(void);static void tick(void*ctx){redraw();schedule();}static void schedule(void){if(timer)app_timer_cancel(timer);time_t e=time(NULL)-s->last_smoked;timer=app_timer_register(e<86400?1000:60000,tick,NULL);}
static void scan_milestone(void){time_t e=time(NULL)-s->last_smoked;for(int i=0;i<MILESTONE_COUNT&&i<31;i++){uint32_t bit=1u<<i;if(e>=MILESTONES[i].seconds&&!(s->notified_mask&bit)){s->notified_mask|=bit;storage_save(s);ach_index=i;view=VIEW_ACH;vibes_double_pulse();break;}}}
static void finish_flash(void*ctx){view=VIEW_HOME;anim=0;redraw();}
static void enter_setting(int i){if(i==0){num_value=s->cigarettes_per_day;number_is_cost=false;view=VIEW_NUMBER;}else if(i==1){num_value=s->money_cents_per_day;number_is_cost=true;view=VIEW_NUMBER;}else if(i==2){cur_pick=s->currency;view=VIEW_CURRENCY;}else if(i==3){time_t n=s->last_smoked;picker_tm=*localtime(&n);picker_field=0;view=VIEW_PICKER;}else view=VIEW_RESET;redraw();}
static void select_click(ClickRecognizerRef r,void*c){if(view==VIEW_HOME)view=VIEW_CONFIRM;else if(view==VIEW_CONFIRM){storage_record_relapse(s,time(NULL));view=VIEW_FLASH;anim=1;redraw();app_timer_register(350,finish_flash,NULL);return;}else if(view==VIEW_ACH){if(ach_index>=0){ach_index=-1;view=VIEW_HOME;}else view=VIEW_HOME;}else if(view==VIEW_STATS){if(row==5){view=VIEW_HISTORY;row=0;}else{view=VIEW_SETTINGS;row=0;}}else if(view==VIEW_SETTINGS){enter_setting(row);return;}else if(view==VIEW_ONBOARD){if(ob==OB_LAST){time_t n=time(NULL);if(row==1){struct tm t=*localtime(&n);t.tm_hour=0;t.tm_min=0;t.tm_sec=0;n=mktime(&t);}else if(row==2)n-=86400;s->last_smoked=n;ob=OB_CIGS;num_value=20;number_is_cost=false;view=VIEW_NUMBER;}else{s->configured=true;storage_save(s);view=VIEW_HOME;}}else if(view==VIEW_PICKER){picker_field++;if(picker_field>4){time_t t=mktime(&picker_tm);if(t>time(NULL))t=time(NULL);s->last_smoked=t;storage_save(s);view=s->configured?VIEW_SETTINGS:VIEW_ONBOARD;picker_field=0;}}else if(view==VIEW_NUMBER){if(number_is_cost)s->money_cents_per_day=num_value;else s->cigarettes_per_day=num_value;storage_save(s);if(!s->configured){if(ob==OB_CIGS){ob=OB_COST;num_value=300;number_is_cost=true;}else if(ob==OB_COST){ob=OB_CUR;cur_pick=s->currency;view=VIEW_CURRENCY;}}else view=VIEW_SETTINGS;}else if(view==VIEW_CURRENCY){s->currency=cur_pick;storage_save(s);if(!s->configured){ob=OB_DONE;view=VIEW_ONBOARD;}else view=VIEW_SETTINGS;}else if(view==VIEW_RESET){storage_reset(s);view=VIEW_STATS;}redraw();}
static void back_click(ClickRecognizerRef r,void*c){if(view==VIEW_HOME){window_stack_pop_all(false);return;}if(view==VIEW_CONFIRM||view==VIEW_STATS||view==VIEW_ACH){view=VIEW_HOME;ach_index=-1;}else if(view==VIEW_HISTORY){view=VIEW_STATS;row=5;}else if(view==VIEW_SETTINGS)view=VIEW_STATS;else if(view==VIEW_RESET||view==VIEW_CURRENCY||view==VIEW_NUMBER||view==VIEW_PICKER)view=s->configured?VIEW_SETTINGS:VIEW_ONBOARD;redraw();}
static void adjust(int d){if(view==VIEW_HOME){view=d>0?VIEW_ACH:VIEW_STATS;row=0;}else if(view==VIEW_ACH&&ach_index<0){row+=d>0?-1:1;if(row<0)row=0;if(row>=MILESTONE_COUNT)row=MILESTONE_COUNT-1;}else if(view==VIEW_STATS){row+=d>0?-1:1;if(row<0)row=0;if(row>5)row=5;}else if(view==VIEW_SETTINGS){row+=d>0?-1:1;if(row<0)row=0;if(row>4)row=4;}else if(view==VIEW_HISTORY){row+=d>0?-1:1;if(row<0)row=0;if(row>=s->history_count)row=s->history_count?s->history_count-1:0;}else if(view==VIEW_ONBOARD&&ob==OB_LAST){row+=d>0?-1:1;if(row<0)row=0;if(row>2)row=2;}else if(view==VIEW_NUMBER){num_value+=d*(number_is_cost?25:1);if(number_is_cost){if(num_value<0)num_value=0;if(num_value>50000)num_value=50000;}else{if(num_value<1)num_value=1;if(num_value>100)num_value=100;}}else if(view==VIEW_CURRENCY){int x=(int)cur_pick+(d>0?-1:1);if(x<0)x=3;if(x>3)x=0;cur_pick=(Currency)x;}else if(view==VIEW_PICKER){if(picker_field==0)picker_tm.tm_mday+=d;else if(picker_field==1)picker_tm.tm_mon+=d;else if(picker_field==2)picker_tm.tm_year+=d;else if(picker_field==3)picker_tm.tm_hour=(picker_tm.tm_hour+d+24)%24;else picker_tm.tm_min=(picker_tm.tm_min+d+60)%60;time_t t=mktime(&picker_tm);picker_tm=*localtime(&t);}redraw();}
static void up(ClickRecognizerRef r,void*c){adjust(1);}static void down(ClickRecognizerRef r,void*c){adjust(-1);}static void clicks(void*c){window_single_click_subscribe(BUTTON_ID_SELECT,select_click);window_single_click_subscribe(BUTTON_ID_BACK,back_click);window_single_click_subscribe(BUTTON_ID_UP,up);window_single_click_subscribe(BUTTON_ID_DOWN,down);window_single_repeating_click_subscribe(BUTTON_ID_UP,120,up);window_single_repeating_click_subscribe(BUTTON_ID_DOWN,120,down);}
static void load(Window*w){Layer*root=window_get_root_layer(w);s_layer=layer_create(layer_get_bounds(root));layer_set_update_proc(s_layer,update);layer_add_child(root,s_layer);}static void unload(Window*w){layer_destroy(s_layer);}
void ui_init(AppState*state){s=state;lang=loc_detect();view=s->configured?VIEW_HOME:VIEW_ONBOARD;ob=OB_LAST;row=0;s_window=window_create();window_set_background_color(s_window,GColorBlack);window_set_click_config_provider(s_window,clicks);window_set_window_handlers(s_window,(WindowHandlers){.load=load,.unload=unload});window_stack_push(s_window,true);if(s->configured){scan_milestone();if(view==VIEW_HOME)app_timer_register(100,intro_tick,NULL);}else intro_phase=4;schedule();}
void ui_deinit(void){if(timer)app_timer_cancel(timer);window_destroy(s_window);}
