top='.'
out='build'

def options(ctx):
    ctx.load('pebble_sdk')

def configure(ctx):
    ctx.load('pebble_sdk')

def build(ctx):
    ctx.load('pebble_sdk')
    if hasattr(ctx, 'features') and 'report_memory_usage' in ctx.features:
        ctx.features.remove('report_memory_usage')
    ctx.pbl_program(
        target='nosmokeblle',
        source=ctx.path.ant_glob('src/c/*.c'),
        features='c cprogram'
    )
